# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ocr_pb2 as ocr__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ocr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OCRServiceStub(object):
    """Error codes (HTTP parity)
    -------------------------
    Every non-OK gRPC response from this service carries a structured error
    code in the trailing metadata under the key "x-error-code". The value is
    the same string the HTTP API returns inside {"error":{"code":"..."}} so
    clients can branch on a single set of identifiers regardless of transport.

    Known codes:
    LAYOUT_DISABLED, INVALID_PARAMETER, BASE64_DECODE_FAILED,
    IMAGE_DECODE_FAILED, DIMENSIONS_TOO_LARGE, EMPTY_BATCH, MISSING_IMAGE,
    MISSING_PDF, INVALID_DPI, INVALID_DIMENSIONS, BODY_SIZE_MISMATCH,
    PDF_RENDER_FAILED, PDF_NOT_AVAILABLE, EMPTY_PDF, SERVER_BUSY,
    INFERENCE_ERROR, NOT_READY, TABLE_BACKEND_DISABLED,
    FORMULA_BACKEND_DISABLED, STRUCTURED_MODE_NO_STRUCTURE.

    The legacy grpc::StatusCode + status message remain primary for older
    clients; "x-error-code" is purely additive. Read it via
    ClientContext::GetServerTrailingMetadata() after the call completes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.unary_unary(
                '/ocr.OCRService/Recognize',
                request_serializer=ocr__pb2.OCRRequest.SerializeToString,
                response_deserializer=ocr__pb2.OCRResponse.FromString,
                _registered_method=True)
        self.RecognizeBatch = channel.unary_unary(
                '/ocr.OCRService/RecognizeBatch',
                request_serializer=ocr__pb2.OCRBatchRequest.SerializeToString,
                response_deserializer=ocr__pb2.OCRBatchResponse.FromString,
                _registered_method=True)
        self.RecognizePDF = channel.unary_unary(
                '/ocr.OCRService/RecognizePDF',
                request_serializer=ocr__pb2.OCRPDFRequest.SerializeToString,
                response_deserializer=ocr__pb2.OCRPDFResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ocr.OCRService/Health',
                request_serializer=ocr__pb2.HealthRequest.SerializeToString,
                response_deserializer=ocr__pb2.HealthResponse.FromString,
                _registered_method=True)


class OCRServiceServicer(object):
    """Error codes (HTTP parity)
    -------------------------
    Every non-OK gRPC response from this service carries a structured error
    code in the trailing metadata under the key "x-error-code". The value is
    the same string the HTTP API returns inside {"error":{"code":"..."}} so
    clients can branch on a single set of identifiers regardless of transport.

    Known codes:
    LAYOUT_DISABLED, INVALID_PARAMETER, BASE64_DECODE_FAILED,
    IMAGE_DECODE_FAILED, DIMENSIONS_TOO_LARGE, EMPTY_BATCH, MISSING_IMAGE,
    MISSING_PDF, INVALID_DPI, INVALID_DIMENSIONS, BODY_SIZE_MISMATCH,
    PDF_RENDER_FAILED, PDF_NOT_AVAILABLE, EMPTY_PDF, SERVER_BUSY,
    INFERENCE_ERROR, NOT_READY, TABLE_BACKEND_DISABLED,
    FORMULA_BACKEND_DISABLED, STRUCTURED_MODE_NO_STRUCTURE.

    The legacy grpc::StatusCode + status message remain primary for older
    clients; "x-error-code" is purely additive. Read it via
    ClientContext::GetServerTrailingMetadata() after the call completes.
    """

    def Recognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizePDF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OCRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=ocr__pb2.OCRRequest.FromString,
                    response_serializer=ocr__pb2.OCRResponse.SerializeToString,
            ),
            'RecognizeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeBatch,
                    request_deserializer=ocr__pb2.OCRBatchRequest.FromString,
                    response_serializer=ocr__pb2.OCRBatchResponse.SerializeToString,
            ),
            'RecognizePDF': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizePDF,
                    request_deserializer=ocr__pb2.OCRPDFRequest.FromString,
                    response_serializer=ocr__pb2.OCRPDFResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ocr__pb2.HealthRequest.FromString,
                    response_serializer=ocr__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ocr.OCRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ocr.OCRService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OCRService(object):
    """Error codes (HTTP parity)
    -------------------------
    Every non-OK gRPC response from this service carries a structured error
    code in the trailing metadata under the key "x-error-code". The value is
    the same string the HTTP API returns inside {"error":{"code":"..."}} so
    clients can branch on a single set of identifiers regardless of transport.

    Known codes:
    LAYOUT_DISABLED, INVALID_PARAMETER, BASE64_DECODE_FAILED,
    IMAGE_DECODE_FAILED, DIMENSIONS_TOO_LARGE, EMPTY_BATCH, MISSING_IMAGE,
    MISSING_PDF, INVALID_DPI, INVALID_DIMENSIONS, BODY_SIZE_MISMATCH,
    PDF_RENDER_FAILED, PDF_NOT_AVAILABLE, EMPTY_PDF, SERVER_BUSY,
    INFERENCE_ERROR, NOT_READY, TABLE_BACKEND_DISABLED,
    FORMULA_BACKEND_DISABLED, STRUCTURED_MODE_NO_STRUCTURE.

    The legacy grpc::StatusCode + status message remain primary for older
    clients; "x-error-code" is purely additive. Read it via
    ClientContext::GetServerTrailingMetadata() after the call completes.
    """

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/Recognize',
            ocr__pb2.OCRRequest.SerializeToString,
            ocr__pb2.OCRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/RecognizeBatch',
            ocr__pb2.OCRBatchRequest.SerializeToString,
            ocr__pb2.OCRBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizePDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/RecognizePDF',
            ocr__pb2.OCRPDFRequest.SerializeToString,
            ocr__pb2.OCRPDFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/Health',
            ocr__pb2.HealthRequest.SerializeToString,
            ocr__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
